### ISSUE TITLE
Bot crashes

### ISSUE THREAD

**Issue by arandomdeadbear** [Tomato6966/discord-audit-log-webhook-with-mongoose#1]
**Describe the bug**
Bot crushes whenever i delete or create any role, ban or unban user...

**HERE IS THE ROLE DELETE ERROR**
`D:\GitBots\discord-audit-log-webhook-with-mongoose-master\logger.js:296
        "ROLE DELETED"`ROLE: ${role}\nROLENAME: ${role.name}\nROLEID: ${role.id}\nHEXCOLOR: ${role.hexColor}\nPOSITION: ${role.position}`
                      ^

TypeError: "ROLE DELETED" is not a function
    at Client.<anonymous> (D:\GitBots\discord-audit-log-webhook-with-mongoose-master\logger.js:296:23)
    at Client.emit (events.js:315:20)
    at GuildRoleDeleteAction.handle (D:\GitBots\discord-audit-log-webhook-with-mongoose-master\node_modules\discord.js\src\client\actions\GuildRoleDelete.js:22:16)
    at Object.module.exports [as GUILD_ROLE_DELETE] (D:\GitBots\discord-audit-log-webhook-with-mongoose-master\node_modules\discord.js\src\client\websocket\handlers\GUILD_ROLE_DELETE.js:4:34)
    at WebSocketManager.handlePacket (D:\GitBots\discord-audit-log-webhook-with-mongoose-master\node_modules\discord.js\src\client\websocket\WebSocketManager.js:384:31)

    at WebSocketShard.onPacket (D:\GitBots\discord-audit-log-webhook-with-mongoose-master\node_modules\discord.js\src\client\websocket\WebSocketShard.js:444:22)
    at WebSocketShard.onMessage (D:\GitBots\discord-audit-log-webhook-with-mongoose-master\node_modules\discord.js\src\client\websocket\WebSocketShard.js:301:10)
    at WebSocket.onMessage (D:\GitBots\discord-audit-log-webhook-with-mongoose-master\node_modules\discord.js\node_modules\ws\lib\event-target.js:132:16)
    at WebSocket.emit (events.js:315:20)
    at Receiver.receiverOnMessage (D:\GitBots\discord-audit-log-webhook-with-mongoose-master\node_modules\discord.js\node_modules\ws\lib\websocket.js:825:20)
    at Receiver.emit (events.js:315:20)
    at Receiver.dataMessage (D:\GitBots\discord-audit-log-webhook-with-mongoose-master\node_modules\discord.js\node_modules\ws\lib\receiver.js:437:14)
    at Receiver.getData (D:\GitBots\discord-audit-log-webhook-with-mongoose-master\node_modules\discord.js\node_modules\ws\lib\receiver.js:367:17)
    at Receiver.startLoop (D:\GitBots\discord-audit-log-webhook-with-mongoose-master\node_modules\discord.js\node_modules\ws\lib\receiver.js:143:22)
    at Receiver._write (D:\GitBots\discord-audit-log-webhook-with-mongoose-master\node_modules\discord.js\node_modules\ws\lib\receiver.js:78:10)
    at writeOrBuffer (_stream_writable.js:378:12)`

**Comment by Tomato6966** [comment]
Fixxed
